In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'Recommend.csv',names=['user_id', 'movie_id', 'rating', 'timestamp'], skiprows=[0])
df

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [3]:
from sklearn.model_selection import train_test_split
n_users = df.user_id.unique().shape[0] 
n_movies = df.movie_id.unique().shape[0]
train_data, test_data = train_test_split(df, test_size=0.25)

In [4]:
train_data_matrix = np.zeros((n_users, n_movies))
for line in train_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    train_data_matrix[int(line[1])-1, int(line[2])-1] = int(line[3] )
train_data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
train_data_matrix.shape

(943, 1682)

In [7]:
test_data_matrix = np.zeros((n_users, n_movies))
for line in test_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    test_data_matrix[line[1]-1, line[2]-1] = line[3]
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [8]:
test_data_matrix.shape

(943, 1682)

In [9]:
from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
movie_similarity = pairwise_distances(train_data_matrix.T, metric='cosine')
mean_user_rating = train_data_matrix.mean(axis=1)[:, np.newaxis] 
ratings_diff = (train_data_matrix - mean_user_rating) 
user_pred = mean_user_rating + user_similarity.dot(ratings_diff) / np.array([np.abs(user_similarity).sum(axis=1)]).T
user_pred

array([[ 1.5799159 ,  0.54579864,  0.44941295, ...,  0.28078364,
         0.2782763 ,  0.28046056],
       [ 1.33481328,  0.27498499,  0.13321592, ..., -0.06739506,
        -0.06920865, -0.06597   ],
       [ 1.35621667,  0.23171665,  0.09620972, ..., -0.1096919 ,
        -0.11118459, -0.10775953],
       ...,
       [ 1.22391921,  0.20892092,  0.07748419, ..., -0.11551419,
        -0.11769528, -0.11434005],
       [ 1.38152869,  0.29483284,  0.18317165, ..., -0.01621295,
        -0.01828046, -0.01520558],
       [ 1.41781514,  0.37155609,  0.27052182, ...,  0.09806061,
         0.09554985,  0.09796902]])

In [11]:
user_pred[0]

array([1.5799159 , 0.54579864, 0.44941295, ..., 0.28078364, 0.2782763 ,
       0.28046056])

In [12]:
max(user_pred[0])

2.186126311745568

In [13]:
np.where(user_pred[0]==max(user_pred[0]))[0][0]

49

In [19]:
max(user_pred[1])

1.993314825045804